ANIME_LIST = [
    {
        "title": "귀멸의 칼날",
        "poster": "assets/posters/kimetsu_no_yaiba.jpg",
        "genres": ["액션", "판타지", "모험"],
        "genre_affinity": {"액션": 1.0, "판타지": 0.85, "모험": 0.75, "드라마": 0.35},
        "year": 2019,
        "rating": 4.7,
        "description": "가족을 잃은 소년이 동생을 구하기 위해 귀살대가 되어 싸우는 이야기.",
    },
    {
        "title": "주술회전",
        "poster": "assets/posters/jujutsu_kaisen.jpg",
        "genres": ["액션", "판타지", "학원"],
        "genre_affinity": {"액션": 1.0, "판타지": 0.9, "학원": 0.65, "스릴러": 0.35},
        "year": 2020,
        "rating": 4.6,
        "description": "저주와 싸우는 주술사들의 빠른 전개와 화려한 전투가 매력인 작품.",
    },
    {
        "title": "하이큐!!",
        "poster": "assets/posters/haikyuu.jpg",
        "genres": ["스포츠", "성장", "학원"],
        "genre_affinity": {"스포츠": 1.0, "성장": 0.9, "학원": 0.65, "코미디": 0.35},
        "year": 2014,
        "rating": 4.8,
        "description": "작은 키의 소년이 배구를 통해 팀워크와 성장을 배워가는 스포츠 애니.",
    },
    {
        "title": "스파이 패밀리",
        "poster": "assets/posters/spy_x_family.jpg",
        "genres": ["코미디", "일상", "액션"],
        "genre_affinity": {"코미디": 1.0, "일상": 0.75, "액션": 0.65, "감동": 0.35},
        "year": 2022,
        "rating": 4.5,
        "description": "스파이, 암살자, 초능력자가 가짜 가족이 되며 벌어지는 따뜻한 코미디.",
    },
    {
        "title": "너의 이름은.",
        "poster": "assets/posters/kimi_no_na_wa.jpg",
        "genres": ["로맨스", "판타지", "드라마"],
        "genre_affinity": {"로맨스": 1.0, "판타지": 0.8, "드라마": 0.85, "감동": 0.65},
        "year": 2016,
        "rating": 4.8,
        "description": "서로 몸이 바뀌는 두 학생이 시간과 운명을 넘어 이어지는 극장판 애니.",
    },
    {
        "title": "바이올렛 에버가든",
        "poster": "assets/posters/violet_evergarden.jpg",
        "genres": ["드라마", "감동", "일상"],
        "genre_affinity": {"드라마": 1.0, "감동": 0.95, "일상": 0.65, "로맨스": 0.3},
        "year": 2018,
        "rating": 4.7,
        "description": "감정을 몰랐던 소녀가 편지를 대필하며 사랑의 의미를 배워가는 작품.",
    },
    {
        "title": "소드 아트 온라인",
        "poster": "assets/posters/sword_art_online.jpg",
        "genres": ["판타지", "액션", "모험"],
        "genre_affinity": {"판타지": 1.0, "액션": 0.85, "모험": 0.8, "로맨스": 0.35},
        "year": 2012,
        "rating": 4.2,
        "description": "가상현실 게임에 갇힌 플레이어들이 생존을 위해 싸우는 이야기.",
    },
    {
        "title": "약속의 네버랜드",
        "poster": "assets/posters/neverland.jpg",
        "genres": ["스릴러", "미스터리", "드라마"],
        "genre_affinity": {"스릴러": 1.0, "미스터리": 0.95, "드라마": 0.7, "두뇌전": 0.65},
        "year": 2019,
        "rating": 4.4,
        "description": "고아원에 숨겨진 진실을 알게 된 아이들이 탈출을 계획하는 긴장감 있는 작품.",
    },
    {
        "title": "데스노트",
        "poster": "assets/posters/death_note.jpg",
        "genres": ["스릴러", "미스터리", "두뇌전"],
        "genre_affinity": {"스릴러": 1.0, "미스터리": 0.9, "두뇌전": 1.0, "드라마": 0.45},
        "year": 2006,
        "rating": 4.8,
        "description": "이름을 쓰면 사람이 죽는 노트를 둘러싼 천재들의 심리전.",
    },
    {
        "title": "케이온!",
        "poster": "assets/posters/k_on.jpg",
        "genres": ["일상", "코미디", "음악"],
        "genre_affinity": {"일상": 1.0, "코미디": 0.75, "음악": 0.8, "학원": 0.55},
        "year": 2009,
        "rating": 4.3,
        "description": "방과 후 밴드부 학생들의 귀엽고 편안한 일상을 그린 음악 애니.",
    },
    {
        "title": "4월은 너의 거짓말",
        "poster": "assets/posters/your_lie_in_april.jpg",
        "genres": ["음악", "로맨스", "드라마"],
        "genre_affinity": {"음악": 1.0, "로맨스": 0.85, "드라마": 0.95, "감동": 0.8},
        "year": 2014,
        "rating": 4.7,
        "description": "피아노를 치지 못하게 된 소년이 바이올린 소녀를 만나 다시 음악과 마주한다.",
    },
    {
        "title": "원펀맨",
        "poster": "assets/posters/one_punch_man.jpg",
        "genres": ["액션", "코미디", "히어로"],
        "genre_affinity": {"액션": 1.0, "코미디": 0.85, "히어로": 0.9, "판타지": 0.35},
        "year": 2015,
        "rating": 4.6,
        "description": "너무 강해서 모든 적을 한 방에 쓰러뜨리는 히어로의 유쾌한 이야기.",
    },
    {
        "title": "나의 히어로 아카데미아",
        "poster": "assets/posters/mha.jpg",
        "genres": ["히어로", "액션", "학원"],
        "genre_affinity": {"히어로": 1.0, "액션": 0.9, "학원": 0.75, "성장": 0.65},
        "year": 2016,
        "rating": 4.4,
        "description": "개성이 없는 소년이 최고의 히어로를 꿈꾸며 성장하는 학원 액션물.",
    },
    {
        "title": "빙과",
        "poster": "assets/posters/hyouka.jpg",
        "genres": ["미스터리", "일상", "학원"],
        "genre_affinity": {"미스터리": 1.0, "일상": 0.75, "학원": 0.7, "두뇌전": 0.45},
        "year": 2012,
        "rating": 4.4,
        "description": "고전부 학생들이 일상 속 작은 수수께끼를 풀어가는 잔잔한 미스터리.",
    },
    {
        "title": "슬램덩크",
        "poster": "assets/posters/slam_dunk.jpg",
        "genres": ["스포츠", "성장", "코미디"],
        "genre_affinity": {"스포츠": 1.0, "성장": 0.9, "코미디": 0.6, "드라마": 0.45},
        "year": 1993,
        "rating": 4.9,
        "description": "농구 초보 강백호가 팀원들과 함께 성장하는 전설적인 스포츠 애니.",
    },
    {
        "title": "체인소 맨",
        "poster": "assets/posters/chainsaw_man.jpg",
        "genres": ["액션", "판타지", "스릴러"],
        "genre_affinity": {"액션": 1.0, "판타지": 0.85, "스릴러": 0.75, "드라마": 0.45},
        "year": 2022,
        "rating": 4.6,
        "description": "채무를 갚기 위해 악마 사냥꾼이 된 소년이 체인소의 힘으로 괴물과 싸우는 다크 액션.",
    },
    {
        "title": "최애의 아이",
        "poster": "assets/posters/oshi_no_ko.jpg",
        "genres": ["드라마", "미스터리", "음악"],
        "genre_affinity": {"드라마": 1.0, "미스터리": 0.9, "음악": 0.65, "스릴러": 0.55},
        "year": 2023,
        "rating": 4.7,
        "description": "연예계를 배경으로 복수와 진실, 빛나는 스타의 삶을 그린 감정적인 이야기.",
    },
    {
        "title": "장송의 프리렌",
        "poster": "assets/posters/frieren.jpg",
        "genres": ["판타지", "모험", "드라마"],
        "genre_affinity": {"판타지": 1.0, "모험": 0.85, "드라마": 0.9, "감동": 0.8},
        "year": 2023,
        "rating": 4.8,
        "description": "마왕을 쓰러뜨린 뒤 긴 여정을 떠나며 인간과의 인연을 되새기는 엘프 마법사의 이야기.",
    },
    {
        "title": "괴수 8호",
        "poster": "assets/posters/kaiju_no_8.jpg",
        "genres": ["액션", "히어로", "판타지"],
        "genre_affinity": {"액션": 1.0, "히어로": 0.9, "판타지": 0.7, "코미디": 0.35},
        "year": 2024,
        "rating": 4.4,
        "description": "청소부가 괴수로 변해 국방부에 입대하며 인류를 지키려는 이색 히어로 액션.",
    },
    {
        "title": "블리치",
        "poster": "assets/posters/bleach.jpg",
        "genres": ["액션", "판타지", "모험"],
        "genre_affinity": {"액션": 1.0, "판타지": 0.9, "모험": 0.75, "성장": 0.55},
        "year": 2004,
        "rating": 4.5,
        "description": "영혼을 보는 소년이 사신이 되어 악령과 사신 세계의 위협에 맞서는 장편 액션.",
    },
    {
        "title": "도쿄 리벤져스",
        "poster": "assets/posters/tokyo_revengers.jpg",
        "genres": ["액션", "드라마", "스릴러"],
        "genre_affinity": {"액션": 0.85, "드라마": 1.0, "스릴러": 0.7, "성장": 0.65},
        "year": 2021,
        "rating": 4.3,
        "description": "과거로 돌아가 어린 시절의 연인을 구하기 위해 갱단과 맞서는 시간여행 드라마.",
    },
    {
        "title": "그 비스크 돌은 사랑을 한다",
        "poster": "assets/posters/bocchi_the_rock.jpg",
        "genres": ["음악", "코미디", "일상"],
        "genre_affinity": {"로맨스": 1.0, "코미디": 0.9, "일상": 0.8, "성장": 0.75},
        "year": 2022,
        "rating": 4.7,
        "description": "극도의 커뮤니케이션 장애 소녀가 밴드 활동을 통해 친구와 음악을 찾아가는 성장물.",
    },
    {
        "title": "강철의 연금술사",
        "poster": "assets/posters/fma.jpg",
        "genres": ["액션", "판타지", "모험"],
        "genre_affinity": {"액션": 1.0, "판타지": 0.9, "모험": 0.85, "드라마": 0.8},
        "year": 2003,
        "rating": 4.9,
        "description": "금지된 연금술의 대가를 치른 형제가 국가의 음모와 맞서며 진실을 찾아가는 대작.",
    },
    {
        "title": "나루토",
        "poster": "assets/posters/naruto.jpg",
        "genres": ["액션", "모험", "성장"],
        "genre_affinity": {"액션": 1.0, "모험": 0.85, "성장": 0.9, "학원": 0.45},
        "year": 2002,
        "rating": 4.7,
        "description": "괴물을 품은 소년이 닌자가 되어 동료와 함께 최고의 호카게를 꿈꾸는 성장 액션.",
    },
    {
        "title": "원피스",
        "poster": "assets/posters/one_piece.jpg",
        "genres": ["액션", "모험", "코미디"],
        "genre_affinity": {"액션": 0.9, "모험": 1.0, "코미디": 0.75, "드라마": 0.55},
        "year": 1999,
        "rating": 4.8,
        "description": "고무고무 열매를 먹은 소년이 해적왕을 꿈꾸며 동료들과 끝없는 바다를 항해한다.",
    },
    {
        "title": "헌터×헌터",
        "poster": "assets/posters/hunter_x_hunter.jpg",
        "genres": ["액션", "모험", "판타지"],
        "genre_affinity": {"액션": 1.0, "모험": 0.9, "판타지": 0.8, "두뇌전": 0.55},
        "year": 2011,
        "rating": 4.8,
        "description": "아버지를 찾기 위해 헌터 시험에 도전하며 강해지는 소년의 모험과 치열한 전투.",
    },
    {
        "title": "진격의 거인",
        "poster": "assets/posters/attack_on_titan.jpg",
        "genres": ["액션", "드라마", "스릴러"],
        "genre_affinity": {"액션": 1.0, "드라마": 0.85, "스릴러": 0.9, "미스터리": 0.7},
        "year": 2013,
        "rating": 4.7,
        "description": "거인에게 점령당한 세계에서 인류를 지키기 위해 벽 밖으로 나서는 생존 전투.",
    },
    {
        "title": "닥터 스톤",
        "poster": "assets/posters/dr_stone.jpg",
        "genres": ["모험", "판타지", "두뇌전"],
        "genre_affinity": {"모험": 1.0, "판타지": 0.75, "두뇌전": 0.85, "코미디": 0.55},
        "year": 2019,
        "rating": 4.5,
        "description": "석화에서 깨어난 소년이 과학의 힘으로 문명을 되살리며 생존과 발명에 도전한다.",
    },
]


def get_all_genres():
    genres = set()

    for anime in ANIME_LIST:
        genres.update(anime["genres"])
        genres.update(anime.get("genre_affinity", {}).keys())

    return sorted(genres)
